tons of additions: safer, neater & better

diff --git a/process-scrobble-log b/process-scrobble-log
--- a/process-scrobble-log
+++ b/process-scrobble-log
@@ -8,71 +8,123 @@
 
 set -e
 
-log=".scrobbler.log"
+logfile=".scrobbler.log"
 
 device="/dev/disk/by-uuid/D057-2F0C"
 mount="/mnt/mp3"
-scrobbledir="$HOME/.mp3scrobbles"
+tmp_dir="$HOME/.mp3scrobbles"
 
+usage() {
+    cat <<EOF
+Usage: ${0##*/} [DIR]
+Retrieve and submit a Rockbox scrobbler log to Last.fm.
+
+If DIR is present, scan it for logs instead of trying to mount MP3
+player.
+EOF
+}
+
+# Log an event.
+log() {
+    echo "${0##*/}: $1"
+}
+
+# Log an error (but don't exit).
+error() {
+    log "error: $1"
+}
+
+# Try to mount device.
 mount_device() {
-    # try to mount device
     sudo mount "$device" "$mount" -o uid=$UID,gid=$UID
 
     # tell how it went
     if [[ $? == 0 ]]; then
-        echo "${0##*/}: mounted succesfully"
+        log "mounted succesfully"
     else
-        echo "${0##*/}: error: could not mount device $device at mount point $mount"
+        error "could not mount device $device at mount point $mount"
         exit 2
     fi
 }
 
+# Try to unmount device.
 unmount_device() {
-    # try to unmount device
     sudo umount "$device"
 
     # tell how it went
     if [[ $? == 0 ]]; then
-        echo "${0##*/}: unmounted successfully"
+        log "unmounted successfully"
     else
-        echo "${0##*/}: error: could not unmount $device"
+        error "could not unmount $device"
         exit 3
     fi
 }
 
-# if device not present, exit
-if [[ ! -e "$device" ]]; then
-    echo "${0##*/}: error: device not present"
+if [[ $# == 1 ]]; then
+    log "using argument as log directory (not mounting)"
+    log_dir="$1"
+elif [[ $# > 1 ]]; then
+    error "expected 0 or 1 arguments (got $#)"
     exit 1
+elif [[ ! -L "$device" ]]; then
+    error "device not present"
+    exit 2
+else
+    log "device found, mounting..."
+    mount_device
+    mount_dir="$mount"
+    log_dir="$mount_dir"
 fi
 
-# mount device
-echo "${0##*/}: device found, mounting..."
-mount_device
+if [[ -f "$log_dir/$logfile" ]]; then
+    # found a scrobbler log
+    if [[ -n "$mount_dir" ]]; then
+        # we mounted, so we make a temporary directory for the log, so
+        # that it's not lost if something breaks
+        tmp_logdir="$tmp_dir/$(date "+%Y-%m-%d")-scrobbler-log"
+        mkdir "$tmp_logdir"
+        mv "$log_dir/$logfile" "$tmp_logdir"
+        log "log moved from device -> $tmp_logdir"
 
-if [[ -f "$mount/$log" ]]; then
-    # make a temporary directory for the log, so that it's not lost if
-    # something breaks
-    newdir="$scrobbledir/$(date "+%Y-%m-%d")-scrobbler-log"
-    mkdir "$newdir"
-    mv "$mount/$log" "$newdir"
-
-    # unmount as soon as possible
-    unmount_device
-
-    # view (& edit) the log (e.g. to delete entries of podcasts)
-    # not really sure if it's useful
-    #vim "$newdir/$log"
-
-    # submit tracks
-    # qtscrob takes it upon itself to delete the file itself, the dirty
-    # program >:(
-    qtscrob-cli --file --location "$newdir"
-
-    # delete temporary directory
-    rm -rf "$newdir"
+        # unmount ASAP so we can unplug
+        unmount_device
+    else
+        # no temp dirs, keep the log where it is
+        tmp_logdir="$log_dir"
+    fi
 else
-    echo "${0##*/}: no scrobbler log present"
-    unmount_device
+    # no log was present
+    log "no scrobbler log present"
+
+    if [[ -n "$mount_dir" ]]; then
+        # unmount if required
+        unmount_device
+    fi
+
+    # exit without errors
     exit 0
+fi
+
+# view (& edit) the log (e.g. to delete entries of podcasts)
+# not really sure if it's useful
+#vim "$tmp_logdir/$logfile"
+
+# submit tracks
+# qtscrob takes it upon itself to delete the file itself, the dirty
+# program >:(
+qtscrob-cli --file --location "$tmp_logdir"
+
+if [[ $? != 1 ]]; then
+    error "qtscrob-cli failed, exiting"
+    exit 3
+elif [[ $? == 0 ]] && [[ -n "$mount_dir" ]]; then
+    # safe to force removal of temp dir
+    log "log successfully submitted"
+    log "deleting temporary dir"
+    rm -R "$tmp_logdir"
+else
+    # succeeded, but we didn't mount, so don't delete dir!
+    log "log successfully submitted"
+    log "not deleting given dir -- if you wish to, run:"
+    echo "rm -R $tmp_logdir"
 fi
